trigger:
  branches:
    include:
    - main
pool:
  vmImage: windows-latest
variables:
  solutionName: Projects
  devServiceConnection: Spark 365 - Dev
  uatServiceConnection: Spark 365 - UAT
  prodServiceConnection: Spark 365 - LIVE
  solutionFolder: solutions/Projects
  managedArtifactName: managed
  srcArtifactName: src
stages:
- stage: Build
  displayName: Export from DEV and Unpack (incl. Canvas apps)
  jobs:
  - job: export_unpack
    displayName: Export & Unpack
    steps:
    - checkout: self
      clean: true
      persistCredentials: true
      fetchDepth: 0
    - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.tool-installer.PowerPlatformToolInstaller@2
      displayName: Power Platform Tool Installer
      inputs:
        AddToolsToPath: true
    - pwsh: "$solutionFolder = \"$(Build.SourcesDirectory)/$(solutionFolder)\"\n$settingsFolder\
        \ = \"$(Build.SourcesDirectory)/pipelines/settings\"\n\nforeach ($f in @($solutionFolder,\
        \ $settingsFolder)) {\n  if (!(Test-Path $f)) {\n    New-Item -ItemType Directory\
        \ -Path $f -Force | Out-Null\n    Write-Host \"Created $f\"\n  } else {\n\
        \    Write-Host \"Exists: $f\"\n  }\n\n  $keep = Join-Path $f \".gitkeep\"\
        \n  if (!(Test-Path $keep)) {\n    New-Item -ItemType File -Path $keep -Force\
        \ | Out-Null\n    Write-Host \"Added placeholder: $keep\"\n  }\n}\n"
      displayName: Scaffold repo folders (solutions/Projects, pipelines/settings)
    - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.whoami.PowerPlatformWhoAmi@2
      displayName: WhoAmI (DEV)
      inputs:
        authenticationType: PowerPlatformSPN
        PowerPlatformSPN: $(devServiceConnection)
    - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.export-solution.PowerPlatformExportSolution@2
      displayName: Export UNMANAGED from DEV
      inputs:
        authenticationType: PowerPlatformSPN
        PowerPlatformSPN: $(devServiceConnection)
        SolutionName: $(solutionName)
        SolutionOutputFile: $(Build.ArtifactStagingDirectory)/unmanaged/$(solutionName)_unmanaged.zip
        Managed: false
        AsyncOperation: true
        MaxAsyncWaitTime: 120
    - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.export-solution.PowerPlatformExportSolution@2
      displayName: Export MANAGED from DEV
      inputs:
        authenticationType: PowerPlatformSPN
        PowerPlatformSPN: $(devServiceConnection)
        SolutionName: $(solutionName)
        SolutionOutputFile: $(Build.ArtifactStagingDirectory)/managed/$(solutionName)_managed.zip
        Managed: true
        AsyncOperation: true
        MaxAsyncWaitTime: 120
    - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.unpack-solution.PowerPlatformUnpackSolution@2
      displayName: Unpack to $(solutionFolder) (process Canvas apps)
      continueOnError: true
      inputs:
        SolutionInputFile: $(Build.ArtifactStagingDirectory)/unmanaged/$(solutionName)_unmanaged.zip
        SolutionTargetFolder: $(Build.SourcesDirectory)/$(solutionFolder)
        OverwriteFiles: true
        ProcessCanvasApps: true
    - pwsh: git clean -fdx
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Git clean workspace
    - pwsh: "git config --global user.email \"devops-bot@spark365.local\"\ngit config\
        \ --global user.name  \"Azure DevOps Pipeline\"\ngit config --global --add\
        \ safe.directory \"$(Build.SourcesDirectory)\"\n\n# Ensure we're on the branch\
        \ that triggered the build (main)\ngit checkout \"$(Build.SourceBranchName)\"\
        \ngit pull --ff-only\n\n# Stage both the unpacked solution and the pipelines/settings\
        \ folder\ngit add \"$(solutionFolder)\" \"pipelines/settings\"\n\nif (git\
        \ diff --cached --quiet) {\n  Write-Host \"No changes to commit.\"\n}\nelse\
        \ {\n  git commit -m \"chore: scaffold folders and update unpacked $(solutionName)\
        \ solution [skip ci]\"\n  git push origin \"$(Build.SourceBranchName)\"\n\
        }\n"
      displayName: Commit scaffold + unpacked solution back to main
    - publish: $(Build.ArtifactStagingDirectory)/managed/$(solutionName)_managed.zip
      artifact: $(managedArtifactName)
      displayName: Publish managed solution artifact
    - publish: $(Build.SourcesDirectory)/$(solutionFolder)
      artifact: $(srcArtifactName)
      displayName: Publish unpacked source
- stage: Deploy_UAT
  displayName: Import MANAGED to UAT
  dependsOn: Build
  condition: succeeded()
  variables:
    system.debug: true
  jobs:
  - deployment: import_to_uat
    displayName: Import to UAT
    environment: UAT
    strategy:
      runOnce:
        deploy:
          steps:
          - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.tool-installer.PowerPlatformToolInstaller@2
            displayName: Power Platform Tool Installer (Deploy-UAT)
            inputs:
              AddToolsToPath: true
          - pwsh: "$ErrorActionPreference = 'Continue'\nWrite-Host \"Checking PAC\
              \ CLI presence and version...\"\n$cmd = Get-Command pac -ErrorAction\
              \ SilentlyContinue\nif ($null -eq $cmd) {\n  Write-Warning \"pac not\
              \ found on PATH. Tool Installer may have failed.\"\n} else {\n  Write-Host\
              \ \"pac path: $($cmd.Source)\"\n  pac --version 2>$null\n  if ($LASTEXITCODE\
              \ -ne 0) {\n    Write-Warning \"pac --version returned $LASTEXITCODE;\
              \ showing 'pac help' instead.\"\n    pac help\n  }\n}\n"
            displayName: PAC CLI presence/version (non-blocking)
            continueOnError: true
          - download: current
            artifact: $(managedArtifactName)
          - pwsh: "Write-Host \"Verifying managed ZIP artifact (UAT)...\"\n$zip =\
              \ \"$(Pipeline.Workspace)/$(managedArtifactName)/$(solutionName)_managed.zip\"\
              \nWrite-Host \"Expected path: $zip\"\nif (Test-Path $zip) {\n  Write-Host\
              \ \"Found managed ZIP.\"\n  Get-ChildItem -Recurse \"$(Pipeline.Workspace)/$(managedArtifactName)\"\
              \ | Format-Table -AutoSize\n} else {\n  Write-Error \"Managed ZIP NOT\
              \ found at $zip\"\n  exit 1\n}\n"
            displayName: Verify managed ZIP exists (UAT)
          - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.whoami.PowerPlatformWhoAmi@2
            displayName: WhoAmI (UAT)
            inputs:
              authenticationType: PowerPlatformSPN
              PowerPlatformSPN: $(uatServiceConnection)
          - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.import-solution.PowerPlatformImportSolution@2
            displayName: Import MANAGED into UAT
            inputs:
              authenticationType: PowerPlatformSPN
              PowerPlatformSPN: $(uatServiceConnection)
              SolutionInputFile: $(Pipeline.Workspace)/$(managedArtifactName)/$(solutionName)_managed.zip
              AsyncOperation: true
              MaxAsyncWaitTime: 60
              PublishWorkflows: false
- stage: Deploy_PROD
  displayName: Import MANAGED to PROD
  dependsOn: Deploy_UAT
  condition: succeeded()
  variables:
    system.debug: true
  jobs:
  - deployment: import_to_prod
    displayName: Import to PROD
    environment: PROD
    strategy:
      runOnce:
        deploy:
          steps:
          - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.tool-installer.PowerPlatformToolInstaller@2
            displayName: Power Platform Tool Installer (Deploy-PROD)
            inputs:
              AddToolsToPath: true
          - pwsh: "$ErrorActionPreference = 'Continue'\nWrite-Host \"Checking PAC\
              \ CLI presence and version...\"\n$cmd = Get-Command pac -ErrorAction\
              \ SilentlyContinue\nif ($null -eq $cmd) {\n  Write-Warning \"pac not\
              \ found on PATH. Tool Installer may have failed.\"\n} else {\n  Write-Host\
              \ \"pac path: $($cmd.Source)\"\n  pac --version 2>$null\n  if ($LASTEXITCODE\
              \ -ne 0) {\n    Write-Warning \"pac --version returned $LASTEXITCODE;\
              \ showing 'pac help' instead.\"\n    pac help\n  }\n}\n"
            displayName: PAC CLI presence/version (non-blocking)
            continueOnError: true
          - download: current
            artifact: $(managedArtifactName)
          - pwsh: "Write-Host \"Verifying managed ZIP artifact (PROD)...\"\n$zip =\
              \ \"$(Pipeline.Workspace)/$(managedArtifactName)/$(solutionName)_managed.zip\"\
              \nWrite-Host \"Expected path: $zip\"\nif (Test-Path $zip) {\n  Write-Host\
              \ \"Found managed ZIP.\"\n  Get-ChildItem -Recurse \"$(Pipeline.Workspace)/$(managedArtifactName)\"\
              \ | Format-Table -AutoSize\n} else {\n  Write-Error \"Managed ZIP NOT\
              \ found at $zip\"\n  exit 1\n}\n"
            displayName: Verify managed ZIP exists (PROD)
          - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.whoami.PowerPlatformWhoAmi@2
            displayName: WhoAmI (PROD)
            inputs:
              authenticationType: PowerPlatformSPN
              PowerPlatformSPN: $(prodServiceConnection)
          - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.import-solution.PowerPlatformImportSolution@2
            displayName: Import MANAGED into PROD
            inputs:
              authenticationType: PowerPlatformSPN
              PowerPlatformSPN: $(prodServiceConnection)
              SolutionInputFile: $(Pipeline.Workspace)/$(managedArtifactName)/$(solutionName)_managed.zip
              AsyncOperation: true
              MaxAsyncWaitTime: 60
